import json
import traceback

from typing import List

from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate

from src.agents.gemini_client import create_gemini_llm, extract_llm_text, parse_llm_json
from src.graph.state import (
    InvestigationState,
    VerifiedFinding
)
from src.debug_log import node_log

from src.api.websockets.relay import sio


class VerificationResult(BaseModel):
    """Verification results generated by the verifier agent."""

    verified_findings: List[VerifiedFinding] = Field(
        default_factory=list,
        description="Validated forensic findings"
    )

    contradictions_detected: List[str] = Field(
        default_factory=list,
        description="Detected contradictions in findings"
    )

    confidence_delta: float = Field(
        default=0.0,
        description="Confidence adjustment after verification"
    )


verifier_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        (
            "You are an Elite DFIR Verification Agent. "
            "Analyze raw Volatility3 outputs. "
            "Identify security findings. "
            "Populate reasoning_chain with forensic interpretation. "
            "Detect contradictions and hallucination risk. "
            "Return ONLY valid JSON matching this exact schema:\n"
            '{{\n'
            '  "verified_findings": [\n'
            '    {{\n'
            '      "id": "unique_string_id_or_uuid",\n'
            '      "title": "Finding Title",\n'
            '      "description": "Forensic description of what was found",\n'
            '      "severity": "CRITICAL",\n'
            '      "evidence_citations": [{{"source": "plugin_name", "key": "value"}}],\n'
            '      "corroborating_plugins": ["plugin_name"],\n'
            '      "mitre_techniques": ["TXXXX"],\n'
            '      "confidence_score": 0.95,\n'
            '      "confidence_label": "High",\n'
            '      "is_hallucination": false,\n'
            '      "reasoning_chain": {{\n'
            '        "interpretation": "forensic interpretation",\n'
            '        "forensic_significance": "forensic significance",\n'
            '        "confidence_justification": "confidence score justification"\n'
            '      }}\n'
            '    }}\n'
            '  ],\n'
            '  "contradictions_detected": ["description of contradiction"],\n'
            '  "confidence_delta": 0.0\n'
            '}}'
        )
    ),
    (
        "user",
        (
            "Plugin Outputs:\n{plugin_outputs}\n\n"
            "Existing Findings:\n{existing_findings}\n\n"
            "Iteration Memory:\n{iteration_memory}\n\n"
            "Validate and extract all findings."
        )
    )
])


async def verify_findings_node(state: InvestigationState) -> dict:

    investigation_id = state.get('investigation_id', 'unknown')

    await sio.emit(
        'agent:state_change',
        {'agent': 'verifier', 'status': 'active'},
        room=f"investigation:{investigation_id}"
    )

    plugin_outputs = state.get('plugin_outputs', {})
    existing_findings = state.get('findings', [])
    iteration_memory = state.get('iteration_memory', {})

    loop_trigger = None
    new_findings = []
    result = VerificationResult()

    optimized_outputs = {}
    for name, out in plugin_outputs.items():
        parsed_data = out.get("parsed", [])[:100]
        optimized_outputs[name] = {"parsed": parsed_data}

    node_log("NODE_START", "analyst", investigation_id)
    try:
        llm = create_gemini_llm(model="gemini-flash-latest", temperature=0.1)
        chain = verifier_prompt | llm

        response = await chain.ainvoke({
            "plugin_outputs": json.dumps(optimized_outputs),
            "existing_findings": json.dumps(existing_findings),
            "iteration_memory": json.dumps(iteration_memory)
        })

        content = extract_llm_text(response)

        try:
            parsed = parse_llm_json(content)
            
            # Preprocess and normalize to ensure Pydantic validation succeeds
            if isinstance(parsed, dict):
                import uuid
                if "verified_findings" not in parsed or not isinstance(parsed["verified_findings"], list):
                    parsed["verified_findings"] = []
                
                cleaned_findings = []
                for f in parsed["verified_findings"]:
                    if not isinstance(f, dict):
                        continue
                    
                    # Ensure id
                    if "id" not in f or not f["id"]:
                        f["id"] = str(uuid.uuid4())
                    
                    # Ensure title and description
                    f["title"] = str(f.get("title", "Untitled Finding"))
                    f["description"] = str(f.get("description", "No description provided"))
                    
                    # Normalize severity
                    sev = str(f.get("severity", "INFO")).upper()
                    if sev == "CRIT":
                        sev = "CRITICAL"
                    if sev == "WARNING":
                        sev = "MEDIUM"
                    if sev not in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
                        sev = 'INFO'
                    f["severity"] = sev
                    
                    # Ensure evidence_citations is List[dict]
                    citations = f.get("evidence_citations", [])
                    if not isinstance(citations, list):
                        citations = [citations] if isinstance(citations, dict) else []
                    cleaned_citations = []
                    for cit in citations:
                        if isinstance(cit, dict):
                            cleaned_citations.append(cit)
                        elif cit:
                            cleaned_citations.append({"source": "unknown", "details": str(cit)})
                    f["evidence_citations"] = cleaned_citations
                    
                    # Ensure corroborating_plugins is List[str]
                    plugins = f.get("corroborating_plugins", [])
                    if not isinstance(plugins, list):
                        plugins = [plugins] if plugins else []
                    f["corroborating_plugins"] = [str(p) for p in plugins]
                    
                    # Ensure mitre_techniques is List[str]
                    mitre = f.get("mitre_techniques", [])
                    if not isinstance(mitre, list):
                        mitre = [mitre] if mitre else []
                    f["mitre_techniques"] = [str(t) for t in mitre]
                    
                    # Ensure confidence score, label, hallucination
                    try:
                        f["confidence_score"] = float(f.get("confidence_score", 0.8))
                    except (ValueError, TypeError):
                        f["confidence_score"] = 0.8
                        
                    f["confidence_label"] = str(f.get("confidence_label", "High"))
                    f["is_hallucination"] = bool(f.get("is_hallucination", False))
                    
                    # Ensure reasoning_chain is AnalystReasoning
                    rc = f.get("reasoning_chain", {})
                    if not isinstance(rc, dict):
                        rc = {}
                    f["reasoning_chain"] = {
                        "interpretation": str(rc.get("interpretation", "No interpretation provided")),
                        "forensic_significance": str(rc.get("forensic_significance", "No significance provided")),
                        "confidence_justification": str(rc.get("confidence_justification", "No justification provided"))
                    }
                    
                    cleaned_findings.append(f)
                
                parsed["verified_findings"] = cleaned_findings
                
                # Ensure other fields in VerificationResult
                if "contradictions_detected" not in parsed or not isinstance(parsed["contradictions_detected"], list):
                    parsed["contradictions_detected"] = []
                else:
                    parsed["contradictions_detected"] = [str(c) for c in parsed["contradictions_detected"]]
                    
                try:
                    parsed["confidence_delta"] = float(parsed.get("confidence_delta", 0.0))
                except (ValueError, TypeError):
                    parsed["confidence_delta"] = 0.0

            result = VerificationResult(**parsed)
        except Exception as parse_err:
            node_log(
                "NODE_ERROR",
                "analyst",
                investigation_id,
                exception=f"JSON parse failed: {parse_err}",
                traceback_str=traceback.format_exc(),
            )
            result = VerificationResult(
                verified_findings=[],
                contradictions_detected=[],
                confidence_delta=0.0
            )
        else:
            node_log("NODE_SUCCESS", "analyst", investigation_id)

        new_findings = [
            f.model_dump()
            for f in result.verified_findings
        ]

        if state.get("benchmark_mode", False):

            true_positives = 0
            false_positives = 0

            for f in new_findings:

                if f.get('severity') in ['CRITICAL', 'HIGH']:
                    true_positives += 1

                elif f.get('is_hallucination'):
                    false_positives += 1

            await sio.emit(
                'benchmark:metrics',
                {
                    "tp": true_positives,
                    "fp": false_positives,
                    "hallucinations": len([
                        f for f in new_findings
                        if f.get('is_hallucination')
                    ]),
                    "confidence_accuracy": 0.92
                },
                room=f"investigation:{investigation_id}"
            )

        if result.contradictions_detected:

            loop_trigger = "CONTRADICTION_DETECTED"

            iter_id = f"iter_{state.get('iteration', 1)}"

            if iter_id not in iteration_memory:
                iteration_memory[iter_id] = {}

            iteration_memory[iter_id][
                'failed_assumptions'
            ] = result.contradictions_detected

    except Exception as e:
        node_log(
            "NODE_ERROR",
            "analyst",
            investigation_id,
            exception=str(e),
            traceback_str=traceback.format_exc(),
        )
        new_findings = []

    all_findings = existing_findings + new_findings

    overall_confidence = (
        sum(
            f.get('confidence_score', 0.0)
            for f in all_findings
        ) / len(all_findings)
        if all_findings
        else 0.0
    )

    if overall_confidence < 0.60 and not loop_trigger:
        loop_trigger = "LOW_CONFIDENCE"

    await sio.emit(
        'investigation:confidence',
        overall_confidence,
        room=f"investigation:{investigation_id}"
    )

    for f in new_findings:

        await sio.emit(
            'finding:created',
            f,
            room=f"investigation:{investigation_id}"
        )

    await sio.emit(
        'agent:state_change',
        {'agent': 'verifier', 'status': 'idle'},
        room=f"investigation:{investigation_id}"
    )

    return {
        "findings": all_findings,
        "overall_confidence": overall_confidence,
        "loop_trigger": loop_trigger,
        "iteration_memory": iteration_memory
    }
